### ISSUE TITLE
How to make macOS detect it when I use CH552 as a tiny keyboard?

### ISSUE THREAD

**Issue by MuseLinn** [DeqingSun/ch55xduino#114]
Hi
Thanks for your maginificent work first.
I want to use CH552 to finish a 3 keys 'CV' keyboard for my girlfriend, writing the code reference to the example HidKeyboard on Windows/Linux, and it works.
When it connected to her macbook (m1), even the leds were anything but shiny. How should I make it work on macOS? Or is there anything wrong on PCB design?
Thanks a lot

**Comment by DeqingSun** [comment]
please describe your problem and attach necessary code and circuit.

**Comment by MuseLinn** [comment]
Problem: Her macbook (m1) doesn't seem to recognize the CH552. I don't know if it's because the circuit is underloaded or if the laptop lacks a certain driver. 😭The schematic is below.
![image](https://user-images.githubusercontent.com/40310493/216802743-7e16a2c2-6d4d-45fb-962d-73176d43d580.png)
Thanks for your help!

**Comment by DeqingSun** [comment]
Use multimeter to test VCC voltage on the computer. It is very likely to be 0V. 

If you convert the TypeC USB on the Mac to TypeA receptacle, and then use a TypeA to TypeC cable for CH552, your board should work.

The problem is you left CC unconnected. You need 5.1K pull down for the host to detect it correctly. Refer to this design.

https://github.com/WeActStudio/WeActStudio.CH552CoreBoard/blob/master/HDK/WeAct-CH55xCoreBoard-V10%20SchDoc.pdf

**Comment by MuseLinn** [comment]
(。・∀・)ノI Got it! Then it works well!

![ddd78e90f2415f9d916778e216b346f](https://user-images.githubusercontent.com/40310493/216804777-3e4e6b88-1a3d-4d34-a28d-597ca5a89ec7.jpg)

I‘ve never realized this problem because my computer only has the TypeA interfaces so I ignore the details. So in the previous learning design, the difference between 'TypeC' and 'Micro-B' in my mind was nothing but different about signal transmission rates, and directly replace the original MicroB circuit with TypeC. I was very grateful for your help! Have a great life!
