### ISSUE TITLE
Cannot send blocks of 64 bytes on USBSerial

### ISSUE THREAD

**Issue by buttim** [DeqingSun/ch55xduino#121]
If I try to write a block of 64 bytes at once on ```USBSerial```, nothing is sent.
The same happens for blocks of 128 or 256 bytes, but not for 32 bytes.
The same thing happens if instead of using ```USBSerial_print_n``` I cycle for 64 times sending a single byte with ```USBSerial_write``` without flushing.

Sample code:
```
__xdata char s[256];

void setup() {
  memset(s,'x',256);
}

void loop() {
  delay(1000);
  USBSerial_print_n(s,64);
}
```

**Comment by DeqingSun** [comment]
It works perfectly well on my computer.

<img width="505" alt="Screen Shot 2023-02-28 at 3 12 27 PM" src="https://user-images.githubusercontent.com/1385273/221967866-abf9c813-68ee-49ef-861f-b014b54f3c32.png">

Might be a compatibility issue? What OS, OS version, CH55xduino version do you use?

**Comment by buttim** [comment]
Sorry for not specifying the details, I thought they were irrelevant in this case.
Windows 10
Arduino IDE 2.0
Ch55xDuino 0.014
I did not test with the serial monitor of the IDE but with Putty.
After your reply I tested more thoroughly with the serial monitor.
I discovered that the output appears but ~10 seconds later.

**Comment by DeqingSun** [comment]
OK I reproduced the bug with my XP virtual machine. The code work for 63 and 65 but not 64. I'll test what was the cause.

**Comment by buttim** [comment]
Thank you. I tried different variations, it does not happen if you flush outside of a 64 bytes boundary.
I gave a look at the source but could not spot any evident coding error

**Comment by DeqingSun** [comment]
As far as I tested. In windows XP if I keep flushing data of 64 bytes, the data will not show up in the serial monitor, but if I flushing data of 64 then another length, they got printed. I'll investigate further later.

**Comment by DeqingSun** [comment]
Some note during investigation:

The data did get sent to computer after each flush. 1st line is debug signal. 2nd and 3rd is USB.
<img width="456" alt="Screen Shot 2023-02-28 at 10 26 21 PM" src="https://user-images.githubusercontent.com/1385273/222038112-e66e48d9-fe5c-44ff-8862-eaa5011260ec.png">

And on my computer. For every 64 seconds, the 64*64 bytes got printed together. So it might be a descriptor issue? Need further testing.

---

After some random search on the internet [nRF52840 USB CDC strange problem on Windows 10](https://devzone.nordicsemi.com/f/nordic-q-a/42120/nrf52840-usb-cdc-strange-problem-on-windows-10). it mentioned:


>I set the size to 64 to maximize the data transaction.
>
>In theory, everything is working as expected, but the problem I see on Windows 10 is that Windows does not receive any data until I send 4096 bytes. When I call 64 times the app_usbd_cdc_acm_write function (64*64 = 4096), then, Windows receives all the data (no data loss).
>
>I tested the same code on a Raspberry pi and I am not having the same issue.
>
>Other funny information is that if I set the size < 64, then, Windows is able to read the data properly (no delay and no buffering).

And an answer said

>That is actually expected behaviour for USB bulk endpoints, and stated as such in the USB 2.0 spec.
>
>In order to receive less than 4096 bytes, the last packet must be smaller than 64 bytes. USB also allows for zero byte packets, which can be used to send any integer multiple of 64 bytes as one transaction.
>
>Note that most CDC example implementations omit this zero packet handling for simplicity.

 Adding a 0 length flush did work. I'll do more testing and try to find the USB 2.0 spec.

---

In USB 2.0 spec, "usb_20.pdf". In chapter _5.8.3 Bulk Transfer Packet Size Constraints_ . It mentioned:

>A bulk transfer is complete when the endpoint does one of the following:
>• Has transferred exactly the amount of data expected
>• Transfers a packet with a payload size less than wMaxPacketSize or transfers a zero-length packet

Since CDC will not have expected data length, a zero-length packet seems needed.

**Comment by buttim** [comment]
A really bizarre specification indeed. Let me know if I can be of any help, and hold on... I might have quite a lot of questions on the USB implementation coming... :)

**Comment by DeqingSun** [comment]
https://github.com/DeqingSun/ch55xduino/commit/8f18a4f2f617334c3eff261343855f1390bc76f9

Should fix the issue.

**Comment by buttim** [comment]
Thanks, very good work
