### ISSUE TITLE
CH552 into sleep mode and wake it up or switch to low power 

### ISSUE THREAD

**Issue by HYDRA0422** [DeqingSun/ch55xduino#160]
I am a beginner, and I am looking for examples of how to put the CH552 into sleep mode and wake it up or switch to low power mode for a project powered by a lithium battery. Could you please tell me if the current examples include any such code? Thank you very much！

**Comment by DeqingSun** [comment]
No the current example does not include any code with sleep. You need to check the datasheet.

**Comment by rew1ndustry** [comment]
so far i have tried this, in setup()

  // preparing for sleep
  ES = 1;  // enable serial interrupts
  EA = 1;  // Global interrupt enable
  SAFE_MOD = 0x55; SAFE_MOD = 0xAA; WAKE_CTRL |= bWAK_BY_USB;
  SAFE_MOD = 0x55; SAFE_MOD = 0xAA; WAKE_CTRL |= bWAK_RXD0_LO;
  SAFE_MOD = 0x55; SAFE_MOD = 0xAA; PIN_FUNC &= ~bUART0_PIN_X;
  // there are other WAKE_CTRL as well, see documentation.

and then just call

  PCON |= 0x01;  // Enter IDLE mode

or

  PCON |= 0x02;  // Enter DEEP SLEEP mode

in my experiments it seems to go to sleep ok, and it seems to wake on USB activity, but so far i cannot get it to wake on incoming serial, as i had hoped.

**Comment by DeqingSun** [comment]
I can not find the post but I remember in the wch support forum, their engineer confirmed the CH552 has limited capacity to keep usb running while sleeping. I forgot the detail but it is basically not doable on CH552.

**Comment by rew1ndustry** [comment]
thank you - that makes sense.  in my experiments i was using USB to monitor the chip and, since it did not go to sleep, i just assumed USB wake up was working to keep it awake.  i can understand how this would shut down, with the chip asleep.

my main problem is that i was hoping i could use UART0 wake on RX, which i think is triggered when the RX pin goes low, but this does not appear to be waking the chip, in my tests (at 16MHz and 3v3).

at the moment i am using RST to restart the chip, but this is not ideal.

are you aware of any pin that would wake the chip properly?

or is there another forum i should be reading, for these details?
