### ISSUE TITLE
Upload new code after after upload HID code

### ISSUE THREAD

**Issue by HamStudioTW** [DeqingSun/ch55xduino#79]
I have upload the test HID code then i want to change some thing then upload it again 
but it show this error

------------------------------------------------------------------
CH55x Programmer by VNPro
------------------------------------------------------------------
Load file as hex
   Loaded 4715 bytes between: 0000 to 12AE
ch375Version 35
CH375GetUsbID 0
Found no CH55x USB

So who can i upload new code?

**Comment by DeqingSun** [comment]
You need to manually pull the d+ line to a vcc with resistor and power cycle the chip. If you have a develop board, that means you need to hold a button and replug usb cable. 

Note you have to upload the sketch quickly after the power cycle, because a new bootloader will timeout after a few seconds.
